version: '3.8'

services:
  # --- 1. BANCO DE DADOS ---
  mongo:
    image: mongo:6.0
    container_name: ocd_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # --- 2. BACKEND (API) ---
  app:
    build: ./backend
    container_name: ocd_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/dashboard_ocd
      - PORT=5000
      - REPORT_USER=${REPORT_USER}
      - REPORT_PASS=${REPORT_PASS}
    depends_on:
      - mongo
    networks:
      - app-network

  # --- 3. WORKER (Processamento em Background) ---
  worker:
    build: ./worker
    container_name: ocd_worker
    restart: always
    environment:
      - API_URL=http://app:5000/api
    depends_on:
      - app
    networks:
      - app-network

  # --- 4. FRONTEND (Aplicação Web) [NOVO] ---
  frontend:
    build: ./frontend
    container_name: ocd_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
      - NUXT_PORT=3000
      - NUXT_HOST=0.0.0.0 # Garante que o Nuxt aceite conexões externas
      - API_BASE_URL=http://localhost:5000
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge