services:
  # Serviço da sua Aplicação NodeJS
  app:
    build: ./backend
    container_name: ocd_backend
    ports:
      - "3000:3000" # Mapeia porta 3000 do seu PC para 3000 do container
    environment:
      - NODE_ENV=production
      # Aqui conectamos ao container 'mongo' e não localhost
      - MONGO_URI=mongodb://mongo:27017/dashboard_ocd
      # Credenciais da API OCD (substitua ou use arquivo .env)
      - OCD_AUTH_USER=asod_app
      - OCD_AUTH_KEY=ef740b73f6f0b20c2bcaa4387236ac70
    depends_on:
      - mongo
    networks:
      - app-network

  # Serviço do Banco de Dados MongoDB
  mongo:
    image: mongo:6.0
    container_name: ocd_db
    ports:
      - "27017:27017" # Permite que você acesse o banco via Compass/Studio3T no seu PC
    volumes:
      - mongo_data:/data/db # Garante que os dados não sumam ao desligar
    networks:
      - app-network

# Definição dos Volumes (Persistência)
volumes:
  mongo_data:

# Definição da Rede
networks:
  app-network:
    driver: bridge