apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocd-worker
spec:
  replicas: 3 # ESCALABILIDADE: 3 máquinas processando tickets
  selector:
    matchLabels:
      app: ocd-worker
  template:
    metadata:
      labels:
        app: ocd-worker
    spec:
      containers:
        - name: worker
          image: ocd-worker:latest # Substitua pela sua imagem buildada
          env:
            - name: API_URL
              value: "http://ocd-app-service:5000/api"